swagger: "2.0"
info:
  description: "API de conversão de temperatura"
  version: "1.0.1"
  title: "Conversão de temperatura"
  contact:
    email: "bruno.botlho.br@gmail.com"
paths:
  /fahrenheit/{valor}/celsius:
    get:
      description: "Converte de Fahrenheit para Celsius"
      produces:
      - "application/json"
      parameters:
      - name: "valor"
        in: "path"
        description: "Valor que será convertido"
        required: true
        type: "number"
      responses:
        "200":
          description: "Resultado da conversão"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Temperatura"
        "400":
          description: "Bad Input Parameter"

  /celsius/{valor}/fahrenheit:
    get:
      description: "Converte de Celsius para Fahrenheit"
      produces:
      - "application/json"
      parameters:
      - name: "valor"
        in: "path"
        description: "Valor que será convertido"
        required: true
        type: "number"
      responses:
        "200":
          description: "Resultado da conversão"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Temperatura"
        "400":
          description: "Bad Input Parameter"

  /echo/{msg}:
    get:
      description: "Return a message"
      produces:
      - "application/json"
      parameters:
      - name: "msg"
        in: "path"
        description: "Mensagem que será retornada"
        required: true
        type: "string"
      responses:
        "200":
          description: "Retorno"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/msg"
        "400":
          description: "Bad Input Parameter"

definitions:
  Temperatura:
    type: "object"
    required:
    - "valor"
    properties:
      valor:
        type: "number"
        example: 500.0
  msg:
    type: "object"
    required:
    - "msg"
    properties:
      valor:
        type: "string"
        example: Azeitona
