apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometeus.io/port: "8080"
        prometeus.io/path: "/metrics"
        prometeus.io/scrape: "true"
    spec:
      containers:
      - name: api
        image: brunobotelhobr/api_conversao:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
        resources:
          requests:
            cpu: "100m"
            memory: "32Mi"
          limits:
            cpu: "200m"
            memory: "64Mi"

--- 
#Local K8s
#apiVersion: v1
#kind: Service
#metadata:
#  name: api-service
#spec:
#  selector:
#    app: api
#  ports:
#  - port: 32080
#    targetPort: 8080
#  type: LoadBalancer

#Okteto
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - name: http
      port: 8080

--- 
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
