apiVersion: v1
kind: Service
metadata:
  name: api-conversao
spec:
  selector:
    app: api-conversao
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  type: NodePort
apiVersion: v1
kind: Service
metadata:
  name: api-conversao
spec:
  selector:
    app: api-conversao
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  type: NodePort
