name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Download Code
        uses: actions/checkout@v2
      - name: DockerHub Login
        uses: docker/login-action@v1.10.0      
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.6.1
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            brunobotelhobr/api_conversao:latest
            brunobotelhobr/api_conversao:${{ github.run_number }}

           
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Download Code
      uses: actions/checkout@v2
        
    - name: Okteto Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.K8S }}
    
    - name: Activate K8s Cluster
      uses: okteto/namespace@master
      with:
        namespace: brunobotelhobr

    - name: Create deployment
      uses: okteto/apply@master
      with:
        manifest: k8s/deployment.yaml
